### ISSUE TITLE
Usage failed

### ISSUE THREAD

**Issue by Hajogg** [2sic/dnn-theme-bootstrap4-instant#1]
Hi Daniel
I Installed bootstrap4 parallel to boostrap3-instant on dnn 9.2 
I get 
`'Das Seitenlayout konnte nicht geladen werden: /Portals/_default/skins/bootstrap 4 instant/default.ascx. Fehler: Die ID DnnLogin wird bereits von einem anderen Steuerelement verwendet.' `
I also uninstalled boostrap3-instant. 
Thanks for help and greetings
Hajo

**Comment by iJungleboy** [comment]
@lucatescari pls check

**Comment by iJungleboy** [comment]
Sorry about this - we checked it now and interestingly it only happens on the install-package, not when you git-clone. We'll try to find the cause and fix it tomorrow.

**Comment by iJungleboy** [comment]
We found the cause :). A Git-commit before the last release merged some files together. @lucatescari will release it again tonight.

**Comment by lucatescari** [comment]
The issue is now fixed with v04.00.01 of the skin.

**Comment by Hajogg** [comment]
thanks, it works
