### ISSUE TITLE
Outdated installation instructions

### ISSUE THREAD

**Issue by Navilois** [2sic/dnn-theme-bootstrap4-instant#15]
Hey!

I believe the [installation instructions](https://github.com/2sic/dnn-theme-bootstrap4-instant/wiki/installation#installing-build-tools-node-gulp) need some updating.
I just installed v04.10. and followed the instructions which left me hanging at [customize and redesign](https://github.com/2sic/dnn-theme-bootstrap4-instant/wiki/customize-and-redesign#start-the-compiler-for-further-customization):

> Then run this from your skin folder: gulp

Since you switched to webpack, this results in [10:49:32] No gulpfile found. I guess it's supposed to be `npm run build-prod`.
Btw, is there a specific reason you removed webpack.dev.js and webpack.prod.js from v04.02.01?

Thank you for the great theme! Excellent job.

**Comment by iJungleboy** [comment]
just updated the docs - thanks for the ping!
