### ISSUE TITLE
"xxxx" showing on the bottom of the page

### ISSUE THREAD

**Issue by eXistenZe** [2sic/dnn-theme-bootstrap4-instant#18]
Not sure if this is caused by 2sxc or the theme, but when I mouse over bellow the menu (on the top of the content pane), a "xxxx" shows on the bottom of the page. The code in the image seems responsible.

![xxxx](https://user-images.githubusercontent.com/26518879/82541957-1bd3ba80-9b49-11ea-8381-a20e2bc1bbb8.jpg)

**Comment by iJungleboy** [comment]
I believe this is a bug with quick-edit, not with the theme. I'll look into it in 2sxc 11.02 or 11.03

**Comment by eXistenZe** [comment]
Any way to disable quick edit on the theme ascx file?

**Comment by iJungleboy** [comment]
don't worry - should be fixed in 1-2 days.

**Comment by eXistenZe** [comment]
It was actually a side question... I always disable quick edit in all my apps. Is there a way to do this theme level?

**Comment by iJungleboy** [comment]
@eXistenZe yes, the html-attribute that disables it is just a simple html attribute. you can put it anywhere, incl. in the theme
