### ISSUE TITLE
Invisible container does not get installed

### ISSUE THREAD

**Issue by Tychodewaard** [2sic/dnn-theme-bootstrap4-instant#7]
If I install the theme on a 9.3.2. the container is not installed although it says so in the documentation.

Could Not Load Container: /Portals/_default/Containers/Invisible Container/default.ascx DotNetNuke.Services.Exceptions.ModuleLoadException: Unhandled error loading module. ---> System.Web.HttpException: The file '/Portals/_default/Containers/Invisible Container/default.ascx' does not exist. at System.Web.UI.Util.CheckVirtualFileExists(VirtualPath virtualPath) at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath) at DotNetNuke.UI.ControlUtilities.LoadControl[T](TemplateControl containerControl, String ControlSrc) at DotNetNuke.UI.Skins.Pane.LoadContainerByPath(String containerPath) --- End of inner exception stack trace ---

**Comment by iJungleboy** [comment]
This is a bug sorry. Pls install manually for now, we'll try to automate the installation.

**Comment by worldheadquarters** [comment]
Could you be a little more specific on installing this manually?

**Comment by Tychodewaard** [comment]
@worldheadquarters just the ftp the theme to the portals/skins/default folder

**Comment by iJungleboy** [comment]
I'll close this, was fixed quite a while ago.
