### ISSUE TITLE
Helper is not supported

### ISSUE THREAD

**Issue by Tychodewaard** [2sic/dnn-theme-bootstrap4-instant#8]
In Visual studio Code, I get an error : The helper directive is not supported.
This refers to : 
- nav
- main
- template.cshtml
- line 6:
`@helper RenderNodes(IList<MenuNode> nodes) {
`

**Comment by iJungleboy** [comment]
In this case VS Code assumes you're using a very new version of razor, which removed that. But in the MVC of DNN this is correct. So either just ignore the error, or find out how to specify an older version of razor for this.
